import type { MarbleType, Profile, Sale, StockMovement } from "@/lib/types";

// Local, in-memory sample data used ONLY when DEMO_MODE=1. This lets the UI
// be previewed without a live Supabase project connected. Not used in
// production builds.

export const DEMO_PROFILE: Profile = {
  id: "demo-admin",
  full_name: "יוסי כהן",
  role: "admin",
  created_at: "2025-01-10T08:00:00Z",
};

export const DEMO_MARBLE_TYPES: MarbleType[] = [
  {
    id: "1",
    name: "Carrara White",
    name_he: "קררה לבן",
    category: "שיש",
    color: "לבן",
    thickness: '2 ס"מ',
    size: '320x160 ס"מ',
    quantity: 12,
    low_stock_threshold: 3,
    location: "אולם תצוגה",
    image_url: null,
    cost_price: 850,
    selling_price: 1450,
    notes: "שיש איטלקי קלאסי, גימור מלוטש",
    created_at: "2025-02-01T08:00:00Z",
    updated_at: "2025-02-01T08:00:00Z",
  },
  {
    id: "2",
    name: "Calacatta Gold",
    name_he: "קלאקטה זהב",
    category: "שיש",
    color: "זהב",
    thickness: '3 ס"מ',
    size: '320x170 ס"מ',
    quantity: 4,
    low_stock_threshold: 3,
    location: "אולם תצוגה",
    image_url: null,
    cost_price: 1400,
    selling_price: 2300,
    notes: "עורקי זהב בולטים, פריט יוקרה",
    created_at: "2025-02-02T08:00:00Z",
    updated_at: "2025-02-02T08:00:00Z",
  },
  {
    id: "3",
    name: "Nero Marquina",
    name_he: "נרו מרקינה",
    category: "שיש",
    color: "שחור",
    thickness: '2 ס"מ',
    size: '300x160 ס"מ',
    quantity: 2,
    low_stock_threshold: 3,
    location: "מחסן ראשי",
    image_url: null,
    cost_price: 950,
    selling_price: 1650,
    notes: "שיש שחור עם עורקים לבנים",
    created_at: "2025-02-03T08:00:00Z",
    updated_at: "2025-02-03T08:00:00Z",
  },
  {
    id: "4",
    name: "Kashmir White",
    name_he: "קשמיר לבן",
    category: "גרניט",
    color: "לבן",
    thickness: '3 ס"מ',
    size: '320x165 ס"מ',
    quantity: 0,
    low_stock_threshold: 3,
    location: "מחסן חיצוני",
    image_url: null,
    cost_price: 1100,
    selling_price: 1900,
    notes: "אזל מהמלאי - יש להזמין",
    created_at: "2025-02-04T08:00:00Z",
    updated_at: "2025-02-04T08:00:00Z",
  },
  {
    id: "5",
    name: "Blue Bahia",
    name_he: "בלו באהיה",
    category: "גרניט",
    color: "כחול",
    thickness: '3 ס"מ',
    size: '280x160 ס"מ',
    quantity: 3,
    low_stock_threshold: 2,
    location: "אולם תצוגה",
    image_url: null,
    cost_price: 2200,
    selling_price: 3600,
    notes: "פריט נדיר ומיוחד",
    created_at: "2025-02-05T08:00:00Z",
    updated_at: "2025-02-05T08:00:00Z",
  },
  {
    id: "6",
    name: "Botticino Classico",
    name_he: "בוטיצ'ינו קלאסיקו",
    category: "אבן טבעית",
    color: "קרם",
    thickness: '2 ס"מ',
    size: '305x160 ס"מ',
    quantity: 15,
    low_stock_threshold: 4,
    location: "מחסן ראשי",
    image_url: null,
    cost_price: 600,
    selling_price: 980,
    notes: null,
    created_at: "2025-02-06T08:00:00Z",
    updated_at: "2025-02-06T08:00:00Z",
  },
];

export const DEMO_SALES: Sale[] = [
  {
    id: "s1",
    marble_type_id: "1",
    quantity: 1,
    sale_price: 1450,
    customer_name: "דוד לוי",
    customer_phone: "050-1234567",
    notes: null,
    sold_at: new Date().toISOString(),
    created_by: "demo-admin",
    marble_type: DEMO_MARBLE_TYPES[0],
  },
  {
    id: "s2",
    marble_type_id: "2",
    quantity: 2,
    sale_price: 2300,
    customer_name: "מטבחי פרימיום בע״מ",
    customer_phone: "03-9998877",
    notes: "משלוח עד הבית",
    sold_at: new Date(Date.now() - 86400000).toISOString(),
    created_by: "demo-admin",
    marble_type: DEMO_MARBLE_TYPES[1],
  },
  {
    id: "s3",
    marble_type_id: "6",
    quantity: 3,
    sale_price: 980,
    customer_name: null,
    customer_phone: null,
    notes: null,
    sold_at: new Date(Date.now() - 86400000 * 20).toISOString(),
    created_by: "demo-admin",
    marble_type: DEMO_MARBLE_TYPES[5],
  },
];

export const DEMO_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: "m1",
    marble_type_id: "1",
    change: -1,
    movement_type: "sell",
    reason: "מכירת לקוח",
    created_at: new Date().toISOString(),
    created_by: "demo-admin",
  },
  {
    id: "m2",
    marble_type_id: "1",
    change: 12,
    movement_type: "create",
    reason: "יצירת פריט חדש במלאי",
    created_at: "2025-02-01T08:00:00Z",
    created_by: "demo-admin",
  },
];
